version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER:-nav_user}:${MYSQL_PASSWORD:-your_password_here}@db:3306/${MYSQL_DATABASE:-nav_site}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: always

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nav_site}
      - MYSQL_USER=${MYSQL_USER:-nav_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-your_password_here}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-your_root_password_here}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    restart: always

volumes:
  mysql_data:
  redis_data:
